const assert = require('node:assert/strict');
require('./filesystem.js');
let value = null, overseer = false, fail = false;
const storage = { getItem: () => value, setItem: (_, next) => { if (fail) throw Error('quota'); value = next; } };
const open = () => RobcoFilesystem.create(storage, () => overseer, () => 'live logs');
const fs = open();
assert.equal(fs.list('/').length, 6);
for (const path of ['/CLASSIFIED', '/PERSONNEL/PERSONNEL.DAT', '/LOGS/OVERSEER.LOG']) assert.throws(() => fs.get(path), /ACCESS DENIED/);
assert.throws(() => fs.create('/CLASSIFIED', 'X.DAT', 'file'), /ACCESS DENIED/);
assert.throws(() => fs.write('/CLASSIFIED/CLASSIFIED.DAT', 'x'), /ACCESS DENIED/);
assert.throws(() => fs.create('/SYSTEM', 'X.DAT', 'file'), /READ-ONLY/);
assert.equal(fs.resolve('SECURITY.DAT'), '/SECURITY/SECURITY.DAT');
assert.equal(fs.normalize('c:\\robco\\vault\\..\\security'), '/SECURITY');
const folder = fs.create('/VAULT', 'test', 'folder');
const file = fs.create(folder, 'note.dat', 'file');
fs.write(file, '<script>literal text</script>\nMixed Case');
assert.equal(open().get(file).content, '<script>literal text</script>\nMixed Case');
assert.throws(() => fs.create(folder, 'note.dat', 'file'), /EXISTS/);
assert.throws(() => fs.create(folder, '../X.DAT', 'file'), /Use/);
assert.throws(() => fs.remove(folder), /empty/);
fs.rename(folder, 'RENAMED');
assert.equal(fs.get('/VAULT/RENAMED/NOTE.DAT').type, 'file');
fs.remove('/VAULT/RENAMED/NOTE.DAT'); fs.remove('/VAULT/RENAMED');
assert.throws(() => fs.remove('/VAULT'), /Built-in/);
overseer = true;
assert.equal(fs.get('/LOGS/OVERSEER.LOG').content, 'live logs');
fs.write('/CLASSIFIED/CLASSIFIED.DAT', 'updated');
assert.equal(open().get('/CLASSIFIED/CLASSIFIED.DAT').content, 'updated');
overseer = false;
assert.throws(() => fs.get('/CLASSIFIED/CLASSIFIED.DAT'), /ACCESS DENIED/);
fail = true;
assert.throws(() => fs.create('/VAULT', 'FAIL.DAT', 'file'), /NOT SAVED/);
assert.throws(() => fs.get('/VAULT/FAIL.DAT'), /NOT FOUND/);
fail = false;
const stale = open(); fs.create('/VAULT', 'NEW.DAT', 'file');
assert.throws(() => stale.create('/VAULT', 'STALE.DAT', 'file'), /another window/);
value = '{broken';
const recovery = open(); assert.match(recovery.warning, /recovery/);
assert.throws(() => recovery.create('/VAULT', 'NO.DAT', 'file'), /preserved/);
assert.equal(value, '{broken');
console.log('PASS: filesystem permissions, paths, CRUD, persistence, protected records, quota rollback, stale saves and corrupt-data recovery.');
