const {chromium}=require('playwright'),fs=require('node:fs'),http=require('node:http'),assert=require('node:assert/strict');
function wav(){const rate=8000,count=rate*8, b=Buffer.alloc(44+count*2);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(rate,24);b.writeUInt32LE(rate*2,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(count*2,40);for(let i=0;i<count;i++)b.writeInt16LE(Math.sin(i*440*2*Math.PI/rate)*1000,44+i*2);return b;}
(async()=>{
const server=http.createServer((req,res)=>{if(req.url==='/test.wav'){const data=wav();res.setHeader('Content-Type','audio/wav');res.setHeader('Accept-Ranges','bytes');const match=/bytes=(\d+)-(\d*)/.exec(req.headers.range||'');if(match){const start=Number(match[1]),end=match[2]?Number(match[2]):data.length-1;res.writeHead(206,{'Content-Range':`bytes ${start}-${end}/${data.length}`,'Content-Length':end-start+1});return res.end(data.subarray(start,end+1));}res.setHeader('Content-Length',data.length);return res.end(data);}const path=__dirname+'/'+(req.url==='/'?'index.html':req.url.slice(1));if(!fs.existsSync(path)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',path.endsWith('.js')?'text/javascript':path.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(path));}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const browser=await chromium.launch({headless:true,channel:'msedge'});
try{
 const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const origin='http://127.0.0.1:'+server.address().port;await page.goto(origin);await page.evaluate(()=>radio.open());const el=n=>page.locator('#radio'+n);
 assert.equal(await el('Play').isDisabled(),true);
 page.once('dialog',d=>d.accept('Expedition mix'));await el('NewStation').click();
 await el('Title').fill('Test signal');await el('URL').fill(origin+'/test.wav');await el('AddURL').locator('button').click();assert.equal(await el('Now').innerText(),'Test signal');assert.equal(await page.evaluate(()=>document.getElementById('radioAudio').paused),true);
 await el('Play').click();await page.waitForFunction(()=>!document.getElementById('radioAudio').paused && document.getElementById('radioAudio').currentTime>0);await el('Play').click();assert.equal(await page.evaluate(()=>document.getElementById('radioAudio').paused),true);
 await el('Seek').fill('3');await el('Seek').dispatchEvent('input');assert.ok(await page.evaluate(()=>document.getElementById('radioAudio').currentTime)>=3);
 await el('Volume').fill('0.22');await el('Volume').dispatchEvent('change');await el('Mute').click();await el('Shuffle').click();await el('Repeat').selectOption('all');
 const requests=[];page.on('request',request=>requests.push(request.url()));
 const chooserReady=page.waitForEvent('filechooser');await el('AddMusic').click();const chooser=await chooserReady;assert.equal(chooser.isMultiple(),true);
 await chooser.setFiles([{name:'local.wav',mimeType:'audio/wav',buffer:wav()},{name:'second.wav',mimeType:'',buffer:wav()},{name:'readme.txt',mimeType:'text/plain',buffer:Buffer.from('skip')},{name:'empty.mp3',mimeType:'audio/mpeg',buffer:Buffer.alloc(0)}]);
 assert.match(await el('Status').innerText(),/SKIPPED 2/);assert.equal(await el('Tracks').locator('button').count(),3);
 await el('Tracks').getByText('second.wav',{exact:true}).click();await page.waitForFunction(()=>document.getElementById('radioAudio').currentTime>0);await el('Play').click();assert.equal(await page.evaluate(()=>document.getElementById('radioAudio').paused),true);
 await el('Files').setInputFiles({name:'bad.wav',mimeType:'audio/wav',buffer:Buffer.from('invalid audio')});await el('Tracks').getByText('bad.wav',{exact:true}).click();await page.waitForFunction(()=>/UNAVAILABLE|UNSUPPORTED/.test(document.getElementById('radioStatus').textContent));
 await el('Files').setInputFiles({name:'readme.txt',mimeType:'text/plain',buffer:Buffer.from('skip')});assert.match(await el('Status').innerText(),/NO AUDIO ADDED/);assert.equal(await el('Files').inputValue(),'');
 await el('Tracks').getByText('local.wav',{exact:true}).click();await page.waitForFunction(()=>document.getElementById('radioAudio').currentTime>0);assert.equal(await el('Play').innerText(),'PAUSE');
 assert.equal(requests.some(url=>/^https?:/.test(url)),false);assert.equal(await page.evaluate(()=>localStorage.getItem('robco.radio.v1').includes('blob:')),false);
 await el('Close').click();assert.equal(await page.evaluate(()=>document.getElementById('radioAudio').paused),true);
 await page.reload();await page.evaluate(()=>radio.open());assert.equal(await el('Volume').inputValue(),'0.22');assert.equal(await el('Repeat').inputValue(),'all');assert.equal(await el('Mute').innerText(),'UNMUTE');assert.equal(await el('Shuffle').getAttribute('aria-pressed'),'true');await el('Play').click();assert.match(await el('Status').innerText(),/RESELECT/);
 await el('Files').setInputFiles({name:'local.wav',mimeType:'audio/wav',buffer:wav()});
 // Synthetic uploads may have a new modification timestamp; select the newly attached entry.
 await el('Tracks').getByText('local.wav',{exact:true}).click();await page.waitForFunction(()=>!document.getElementById('radioAudio').paused);await el('Play').click();
 await el('Up').click();await el('Down').click();await el('Next').click();await el('Previous').click();
 await el('Repeat').selectOption('one');await el('Tracks').getByText('local.wav',{exact:true}).click();await page.waitForFunction(()=>!document.getElementById('radioAudio').paused);await page.evaluate(()=>document.getElementById('radioAudio').dispatchEvent(new Event('ended')));await page.waitForFunction(()=>!document.getElementById('radioAudio').paused);await el('Play').click();
 await el('URL').fill('https://user:pass@example.com/a.mp3');await el('AddURL').locator('button').click();assert.match(await el('Status').innerText(),/without credentials/);
 await el('URL').fill(origin+'/missing.mp3');await el('Title').fill('Broken signal');await el('AddURL').locator('button').click();await el('Tracks').getByText('Broken signal',{exact:true}).click();await page.waitForFunction(()=>/UNAVAILABLE|SIGNAL LOST/.test(document.getElementById('radioStatus').textContent));
 await page.screenshot({path:require('node:os').tmpdir()+'/fallout-radio-desktop.png'});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:require('node:os').tmpdir()+'/fallout-radio-mobile.png'});
 page.once('dialog',d=>d.accept());await el('Remove').click();page.once('dialog',d=>d.accept('Renamed mix'));await el('RenameStation').click();assert.match(await el('Station').innerText(),/Renamed mix/);page.once('dialog',d=>d.accept());await el('DeleteStation').click();assert.equal(await el('Station').locator('option').count(),1);
 const ids=await page.locator('[id]').evaluateAll(nodes=>nodes.map(n=>n.id));assert.equal(ids.length,new Set(ids).size);assert.deepEqual(errors,[]);console.log('PASS: real URL/local playback, pause/seek, settings reload, reattachment, reorder, next/previous, repeat, error handling, station CRUD and mobile.');
}finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exit(1)});
